### ISSUE TITLE
APIban áttérés virid-ról auth.sch internal_id-ra

### ISSUE THREAD

**Issue by tmichel** [kir-dev/korok#114]
Most virid-t használnak az api végpontok a felhasználó azonosítására. A jövőben a virid-t ki szeretnénk vezetni a köztudatból. Jó lenne ha az csak a backend belső ügy lenne. Ezért a `users/{auth_sch_internal_id}/*`-ra kéne áttérni.

Ehhez kell egy új mező a users táblában, valamint az apiban mindenhol le kell cserélni a virid-t az auth.sch id-ra. Ezzel együtt a usert betöltő query-ket is át kell írni.

**Comment by vbalazs** [comment]
Most lenne jó, ha lehetne User Story-t / sub issue-kat felvenni githubon :)

**Comment by zolij** [comment]
@tmichel a mostani profile API-t ne módosítsd (gondolok itt arra, amit IRC-en írtál), mert authsch-n is módosítani kell dolgokat hogy ne szálljon el az egész. Ha kész lesz az új API, akkor átírom arra és utána lehet megszüntetni a mostanit (és a virid kiadását).

**Comment by tmichel** [comment]
@zolij nem gondoltam, hogy azonnal módosítom, előre egyeztetünk majd. de ezt még szeptember előtt. valószínűleg.

**Comment by tmichel** [comment]
Ez közben változott. Marad a virid az apiban.
