### ISSUE TITLE
régi WS-ek támogassák paraméterként az internal_id -t

### ISSUE THREAD

**Issue by zolij** [kir-dev/korok#139]
Mivel az új usereknél már nem tárolódik le a neptun kód, így a következő féléves hálóregnél nem tudná az authsch-s átállás utáni usereket feloldani. A feladat ennek megfelelően hogy a ws-ek támogassák az internal_id alapján történő keresést is. Mivel folyamatosan használt service-ről van szó, így a neptun kódos keresést a félév végéig szintén támogatni kell.

Érintett webservice-k:
- entrants
- memberships

Az éles szerverre történő deploy csak szeptember 10. után történjen meg.

**Comment by tmichel** [comment]
#140-es megoldja ezt
