### ISSUE TITLE
Email szövegek be vannak égetve a .java fájlokba.

### ISSUE THREAD

**Issue by tmichel** [kir-dev/korok#18]
Az emailek szövegét egy külön fájlba/property-be kell kimozgatni.

Pl: LdapManagerBean.java

**Comment by vbalazs** [comment]
maradt még egy kis meló a TimerServiceBeanben, de azt bonyolultabb lenne kibogarászni, most nem biztos, hogy megéri az időt.

a lényeg, hogy nagyrészt sikerült kiírtani a dolgot, a webrétegből már nem is lehet emailt küldeni. ezentúl már lehet használni a kidolgozott módszert.
