### ISSUE TITLE
Regisztrációnál az emailben elküldjük a jelszót is. 

### ISSUE THREAD

**Issue by tmichel** [kir-dev/korok#19]
Regisztrációs megerősítő emailbe nem küldjük el a plain text jelszót!
A regisztrációs folyamatot is felül kellene vizsgálni.

**Comment by vbalazs** [comment]
Ahogy látom ez ki lett szedve valamikor.
Egyedül az admin általi felhasználó létrehozáskor jelentkezett ez a probléma, a `CreateNewPerson` oldalból kiindulva. Ha az admin létrehoz egy felhasználót, akkor egy random 10 karakteres jelszó kerül beállításra, amely jelen állás szerint nem kerül kiküldésre.

Ehhez kapcsolódik, hogy jelenleg a User#confirmationCode-ot sehol nem állítjuk be, egyedül olvassuk a `ConfirmPage`-ben.

**Comment by tmichel** [comment]
A confirmation code-t a `CreateCommunityProfile` page-n állítottuk be régen, de ez most törlődött. Gondolom a regisztrációnál lenne érdemes beállítani. Egyáltalán küldünk még megerősítő emailt? :)

**Comment by vbalazs** [comment]
Jelenleg nem küldünk semmilyen esetben megerősítő emailt. Ki kell találni, hogy hogyan működjön ez pontosan, mikor és mit küldjünk. Ehhez megnézem a #45 működését, hogy aztán ne kelljen elölről kezdeni.

**Comment by tmichel** [comment]
Speciális eset, ha az admin regisztrál be egy új felhasználót (#48). Ekkor a felhasználó még nem kap jelszót. Azt **mindenképpen** szeretnénk elkerülni, hogy jelszót plain textben küldjünk ki a felhasználóknak. Ebben az esetben a megerősítő oldal egy picit bonyolultabb lesz. Két feladatot kell ellátnia:
- Rendes regisztráció, a user accountjához csak megerősítés szükséges, ilyenkor már rendelkezik érvényes jelszóval
- Admin regisztrálja be a usert: ilyenkor még nincs érvényes jelszó, így a megerősítés mellett egy jelszót is be kell kérni a felhasználótól.
