### ISSUE TITLE
Regisztráció átalakítása

### ISSUE THREAD

**Issue by vbalazs** [kir-dev/korok#20]
- régi VIR regisztráció törlése a kódból _(supportra irányítjuk az ilyen kéréseket)_
- aktív villanykaros reg neptunnal - mindig latszódjon
- gólyaidőszak idején új regek
  - reg om azonosítóval
  - reg neptun kóddal

A meglévő `neptun_list` táblát ki kell egészíteni a következő attribútumokkal
- om azonosító
- gólya-e

A gólyatábor után a neptun_list táblában kézzel át kell billenteni a gólyáknak a flaget false-ra.

**Comment by vbalazs** [comment]
@hgabor a rególyák miatt végül lehet, hogy mégis tiltanunk kell az atkív villanykaros reget a gólyaidőszak alatt... Esetleg következő évben lehetne már engedélyezni, feltéve, ha a gólyákat nem feltétel nélkül tesszük át aktív az listába, hanem az aktív hallgatói lista alapján. Így azok, akik passzívra mennek maradnak gólya állapotban. Ezzel csak az a baj, hogy ilyen lista legkorábban is csak reg hét után van, addigra meg már bőven ki kell kapcsolni PéK-en a gólyaidőszakot.

**Comment by hgabor** [comment]
@vbalazs 
Rególyák már úgyis tudják a poént. Ha jelentkezni akarnak GTB-be, akkor külön megkeresik a seniorgárdát, és megkérnek minket, hogy a létező VIR accot állítsuk át gólyára.
Akik kétpasszívra mennek, azok szintén benne szoktak lenni a gólyalistában. Az aktív listáva összenézve inaktiválhatjuk a fiókjukat. Az, hogy pár hétig aktívak lesznek, sztem nem para.

**Comment by vbalazs** [comment]
> https://redmine.kirdev.sch.bme.hu/issues/447
> help dobozok: hogy kell felépülnie egy jelszónak, felhasználói névnek, mely mezők kötelezőek, mire kell figyelni, kapsz értesítést a végén, hogy aktíválnod kell magad, ilyesmik.
