### ISSUE TITLE
Person osztály refaktorálása

### ISSUE THREAD

**Issue by vbalazs** [kir-dev/korok#21]
Át kell gondolni a Person szerepét:
- csak egy logikai entitás legyen, ami nem tud arról, hogy az ldapban hogyan vannak tárolva az attribútumai, a transzformációkat máshol végezzük el
- ténylegesen ebben megvalósítani az ldap transzformációkat, plusz mezők felesleges használata nélkül (viszont így logika kerül az entitásba)

**Comment by tmichel** [comment]
új koncepció szerint ez már elévült.
