### ISSUE TITLE
Teszt vir adatábázis és címtár létrehozása

### ISSUE THREAD

**Issue by tmichel** [kir-dev/korok#23]
1. legyen elérhető közös címtár és teszt adatbázis stewie-n (?), ne kelljen mindenkinek localban összeszopkodni.
2. legyen leírás arról, hogyan kell a teszt szerveren belőni a postgresql-t és az opendj-t
3. jelenjen meg a fejlesztői doksiban, hogyan kell csatlakozni a távoli adatbázishoz
4. a teszt adatbázisba az adatok csak anonimizálás után kerüljenek be

**Comment by vbalazs** [comment]
[doksi a wikin](https://redmine.kirdev.sch.bme.hu/projects/vip/wiki/Tesztadatok_gener%C3%A1l%C3%A1sa_haszn%C3%A1lata_stewien)

még a portokat meg kell nyitni, tűzfalat kell konfigurálni

**Comment by vbalazs** [comment]
[todo, `sequel_pg` gemnek utánanézni](https://github.com/kir-dev/korok/commit/067b0edd88232fb0e4a93d65d7b989c3b14cb85e#commitcomment-3578675)

**Comment by vbalazs** [comment]
portok megnyitva, doksi frissítve
