### ISSUE TITLE
Függőségek és felhasznált libek frissítése

### ISSUE THREAD

**Issue by tmichel** [kir-dev/korok#27]
Szerencsére a legtöbb függőséget egészen jól karbantartottuk, de van néhány, ahol már elég régi verziót használunk. Valamint érdemes lenne a `pom.xml` fájlokat is átnézni és egységesíteni.

Egy már biztos van: apache commons lang 2.4 -> 3-as migrálást el kell végezni.

**Comment by vbalazs** [comment]
a commons lang lehet, hogy pont nem is kell már, mint ha a springldap miatt kellett volna...

**Comment by tmichel** [comment]
a commons lang a confirmation code generálás miatt kell. és a web projektbe van behúzva. nem tudom máshol használtuk-e. most bedobtam a 3.1es verziót a fő pomba és a domainben is használom. de én nem dobnám ki, mert sajnos mindig van valami, ami a jdk-ban nincs megoldva és külső lib kell hozzá, ha nem akarom kézzel újra lekódolni.
