### ISSUE TITLE
Utolsó login nyilvántartása

### ISSUE THREAD

**Issue by tmichel** [kir-dev/korok#30]
Jó lenne nyilvántartani, hogy melyik felhasználó mikor lépett be utoljára. Lehetséges, hogy ezt OpenAM-en keresztül kéne menedzselni.

A bevezetés után fél/egy év alatt kiderülne, hogy ténylegesen ki az inaktív felhasználó. Ez nagyban könnyítené a címtár (#24) és a virdb adattisztítást a jövőben.

**Comment by vbalazs** [comment]
ezt a postprocessing modulban kellene megvalósítani. lehet, hogy valaki nem a PéKbe lép be, hanem mindig federációban lévő oldalakra.

edit: see kir-dev/vir_postprocessing#1
