### ISSUE TITLE
Google Analytics mellőzése DEVELOPMENT környezetben

### ISSUE THREAD

**Issue by tmichel** [kir-dev/korok#31]
Jelenleg a fejlesztés közben is küldjük a nézettségi statisztikákat GA-ba.

Két opció:
- kapcsoljuk ki teljesen a fejlesztés idejére (+1 részemről)
- legyen külön GA tracking kód és használjuk azt

**Comment by vbalazs** [comment]
ez elvileg már fixed
https://github.com/kir-dev/korok/commit/556c974369521bd6a133f4272e9fb85b60de4d5f

https://github.com/kir-dev/korok/blob/556c974369521bd6a133f4272e9fb85b60de4d5f/sch-pek-web/src/main/java/hu/sch/web/wicket/components/choosers/GoogleAnalyticsScript.java#L17

**Comment by tmichel** [comment]
és tényleg megvan már, csak sikerült átnézni rendesen a kódot.
