### ISSUE TITLE
LDAP hozzáférés ne mindig root userként történjen

### ISSUE THREAD

**Issue by tmichel** [kir-dev/korok#35]
Jelenleg a felhasználó a címtárhoz mindig admin felhasználón keresztül fér hozzá, miközben csak néhány olyan művelet van, aminél ez indokolt.

Utána kell nézni, hogy a címtárban a mezei felhasználóknak milyen jogosultságaik vannak.
- Milyen bejegyzéseket tudnak módosítani? Csak saját magukat, vagy mindenki mást is?
- Tudnak-e keresni?

A regisztrációhoz (új felhasználó bejegyzése a címtárba) mindenképpen admin jogkör kell.

**Comment by tmichel** [comment]
Ez lehet, hogy mégsem megvalósítható, mert a felhasználó jelszava nem áll rendelkezésre, amivel LDAP-on keresztül tudnánk bindolni az OpenDJ-hez. A users táblában semmiképp nem lenne jó tárolni a jelszót csak azért, hogy az ldaphoz a user nevében férjünk hozzá.

Esetleg jó lenne egy nem admin felhasználó is a címtárban. Ekkor lehetne, hogy a nem admin köteles műveletek ezen a csökkentett jogkörű felhasználón keresztül történjenek.

**Comment by vbalazs** [comment]
valóban, ezt vegyük ki ebből a milestone-ból, később foglalkozunk ezzel

**Comment by vbalazs** [comment]
ez totál deprecated
