### ISSUE TITLE
EJB rétegben a user kezelés kiegészítése

### ISSUE THREAD

**Issue by tmichel** [kir-dev/korok#36]
A felvett új attribútumokat is kezelni kell az ejb rétegben. Egységesíteni kell a Person és a User osztály manipulálását. Ezzel párhuzamosan az LDAP-hoz kapcsolódó osztályokat át kell alakítani és felkészíteni arra, hogy már csak szinkronizálási szerepük van. Ide kapcsolódik a #35 is.

User kezeléssel kapcsolatos EJB interfészek:
- `EntitlementManagerLocal`: ezt kidobjuk a `CreateCommunityProfile`-lal együtt.
- `LdapManagerLocal`: ezt kidobjuk és az LDAPos dolgokat az EJB rétegben kezeljük teljesen, nem lesz hozzá interfész a webréteg felé.
- `UserManagerLocal`: a userkezelés és a körök kezelése egy EJB-be összemosva. Ezeket szét kell bontani: usermanager és groupmanager. Címtár szinkronizáció itt!
- regisztrációhoz tartozó ejb (még portolásra vár a 2.5.x branchből) User entitást hozzon létre és ne Person-t. Mentsen a db-be, címtárba csak amit kell.

**Comment by tmichel** [comment]
már csak a regisztráció portolása hiányzik. 

összes ldap művelet az `LdapSynchronizer` osztályon keresztül.

**Comment by vbalazs** [comment]
a `UserManagerBean::createUser` [metódusában](https://github.com/kir-dev/korok/blob/master/sch-pek-ejb-impl/src/main/java/hu/sch/ejb/UserManagerBean.java#L131) a persistet nem kellene inkább a `sync.createEntry(user, password, status);` sor után tenni? így "tranzakcionálisabb" jellegű lenne. Most simán lehet az, hogy a db-be beszúrja, de az ldapba nem sikerült, ezt kézzel kezelni utána macerás. ha para van, akkor ne is mentse inkább.

**Comment by vbalazs** [comment]
reg merge: 927615f63, ca1d42f9c (#33)

**Comment by vbalazs** [comment]
88f04d90a5dceacdf506d37fc9784a70fed88860
