### ISSUE TITLE
Ajánlott profilképeknél áttérni BLOBos tárolásról a fájlrendszerre

### ISSUE THREAD

**Issue by tmichel** [kir-dev/korok#38]
Jelenleg a képeket, amiket a gólyáknak profilképként ajánlunk, adatbázisban BLOB-ban tároljuk. Ahogy profilképeknél is, úgy itt is át kellene térni arra, hogy a fájlrendszerben tároljuk a képeket.

Kellene:
- `SpotImage` osztályt módosítani
- SQL-t írni
- átnézni a folyamatot ejb és web oldalon is
- régi képeket kidobni az adatbázisból, már úgysem használhatóak
- wicket oldalon felkészülni arra, hogy fájlrendszerből olvassa fel a képeket

**Comment by tmichel** [comment]
Ebbe menet közben bele kellett nyúlnom. 

A következők készültek el:
- `SpotImage` módosítás
- SQL

Új részfeladatként bejön a SPOT képek felöltésének a kezelése. Ez a `ImageManagerBean` ejb-ben van megvalósítva. Itt is a fájlrendszerben kell tárolni a képeket. Érdemes lehet egy helyen tárolni a profilképekkel.

Ezen túl létre kell hozni egy új konfigurációs pontot, ahol beállítható a képek tárolási helye.

Figyelni kell arra is, hogy a képeket a fájlrendszerben is töröljük, ha az entitás törlődik (`SpotImage`-nél különösen).

**Comment by tmichel** [comment]
Szerintem a SPOT képek betöltésének felesleges egy EJB-t fenntartani. A kép importáló folyamatot egy scriptbe is ki lehet nyomni. Ráadásul ez az importálás valójában csak évente 1x történik, a gólyatábor után

**Comment by vbalazs** [comment]
:+1:

**Comment by tmichel** [comment]
Import scriptben lehet, hogy jó lenne a fájlokat átnevezni és nem az eredeti neptun kódot tartalmazó fájlnevet használni.

**Comment by vbalazs** [comment]
Privacy? vagy van valami egyéb oka?

**Comment by tmichel** [comment]
igen privacy, meg hogy legyen egy konzisztens elnevezési konvenció a képekre, amit a fájlrendszerben tárolunk

**Comment by vbalazs** [comment]
számolhatnánk rájuk sha1 hasht és lehetne az a nevük. :icecream:

**Comment by tmichel** [comment]
akár azt is lehet. sőt. ez jó is lesz és akkor tök mindegy, hogy milyen formában kerül le a userhez, akár a fájlnév is megjelenhet. :) és akkor a teljes fájlra számolunk egy sha1et vagy md5öt ez már tökmindegy.

**Comment by vbalazs** [comment]
valójában igen.
dönthetünk performancia okokból md5 mellett is, de ezt mérni kellene (a mai processzorok elvileg tartalmaznak utasítást a sha hash számításra, szóval nem biztos, hogy jelentkezik különbség).

a mediawiki md5-öt használ a latex képek rendszerezéséhez, én a sha párti vagyok :) bár gyakorlatban ~500 képnél nem jelentkezhet hash collision.
