### ISSUE TITLE
Event, EventType egységesítés

### ISSUE THREAD

**Issue by tmichel** [kir-dev/korok#39]
Úgy tűnik a `Log` entitás a körökkel kapcsolatos egyes eseményeket hivatott rögzíteni. Jó lenne tudni pontosan mire is jó. Ennek a kiderítése a feladat első része.

A feladat kódolós része pedig az lenne, hogy az `Event` és `EventType` osztályokat vonjuk össze. Az `Event` most egy entitás, de valójában csak egy id és egy `EventType` típusú mező összekapcsolva. Jelenlegi formájában nem sok értelme van. Egy felesleges réteg, mert az enummal a redeploy nélküli kiterjesztés lehetőségét megöli, ellenben bevezet felesleges rétegeket.

Két lehetőség:
- `Event` megszűntetése és `EventType`-pal helyettesítjük mindenhol. Elveszik a redeploy nélküli bővíthetőség, de átláthatóbb lesz.
- `EventType` megszűntetése, az `Event` megtartása, és az EventType helyett csak stringet használunk. Nehézkesebb kezelés, de runtime kiterjeszthető. Bár a kód most arról tanúskodik, hogy erre nincs semmi szükség.

Az DB sémát mindenképpen módosítani kell.

**Comment by vbalazs** [comment]
A `Log` entitás valóban a körökkel, pontozásokkal kapcsolatos események tárolására szolgál. Naplózzuk ezeket az eseményeket és időnként reportokat küldünk az érintetteknek (körvezetők, SVIE), lásd `TimerServiceBean`.

**Comment by vbalazs** [comment]
fixed in 0d1efdfb2fac
