### ISSUE TITLE
SVIE elsődleges körként jelölhető olyan kör, ahol öregtag vagyok

### ISSUE THREAD

**Issue by vbalazs** [kir-dev/korok#4]
Gancska jelezte, hogy nem logikus működés az, hogy ha az elsődleges kör választó listában megjelennek azok a körök, amikben öregtag vagyok már.

(redmine issue: #990)

**Comment by Ksisu** [comment]
Hogy ne lehessen kiválasztani az már megvan, igaz még tesztelni kell. Viszont mi van akkor ha valakinek van egy SVIE elsődleges köre és ott lesz egyszer csak öregtag?

**Comment by vbalazs** [comment]
> Viszont mi van akkor ha valakinek van egy SVIE elsődleges köre és ott lesz egyszer csak öregtag?

Az nem para, rendes működés.

**Comment by Ksisu** [comment]
Teszteltem kézzel működik. De mi lesz a SVIE tagsággal? megszűnik vagy automatikusan átállítja egy random másik körre az elsődlegest?

**Comment by vbalazs** [comment]
Semmiképpen nem szűnik meg. Nem történik semmi vele.
Ha ennél több kérdésed van, akkor egy SVIE illetékest kell keresni, hogy ők mit szeretnének. De ennyire nem egyszerű, mert lehet, hogy más körben még aktív, mikor az elsődleges körében öregtaggá teszik. Tehát a SVIE tagsága nem csak egy körtagságától függ (sőt, tudtommal egyáltalán nem függ a körtagságoktól)
