### ISSUE TITLE
Migráló script (címtár -> db)

### ISSUE THREAD

**Issue by tmichel** [kir-dev/korok#43]
Lépések
- "közösségi profil" (db rekord) létrehozása annak, akinek még nincs
- not null mezőkre figyelni, ha címtárban nincs kitöltve:
  - usr_screen_name ahol nincs legyen userXXX
  - usr_gender: legyen not specified
  - usr_student_status: inaktív
- privát attribútumokat is migrálni kell, mert az új modellben minden privát alapból így senkinek semmi nem látszik a profiljából
- címtárból a képeket kinyerni és a megfelelő helyre menteni
- ha valakinek van vir_id-ja es nincs a db-ben (ez elvileg nem lehet), az hiba, naplózzuk.

Menet közben felmerült dolgok:
- hallgatói státusz: új default érték: `UNKNOWN`, hozzáadni az enumhoz is java kódban - ok
- user status áthozása - ok (db schema updated),
- user password áthozása - ok (db schema updated)
- encoding - ok (valamiért a ruby ldap impl benézi az utf-8at ascii-8bitnek)
- virid nélkül, de neptunnal létezők: vannak olyan userek, akiknek a címtárban ugyan nincs viridjuk, de neptun szerint pedig szerepelnek. ezért neptun szerint keresünk a db-ben ha van neptun a címtárban, de nincs vir id. új rekordot csak akkor hozunk létre, ha még így sem találunk semmit az adatbázisban - ok
- vannak olyan rekordok, amik neptun szerint 2x szerepelnek az adatbázisban: egyszer nagybetűs, egyszer kisbetűs neptunkóddal. ezekkel kell kezdeni valamit. sajnos van eltérés az adatokban, ki kell deríteni, hogy melyik is az érvényes. a címtárban is van-e duplikáció.
  
  ```
  select * from users where usr_neptun in (select upper(usr_neptun) 
      from users where upper(usr_neptun) != usr_neptun);
  ```

**Comment by vbalazs** [comment]
@tmichel ezzel tudnál foglakozni?

**Comment by tmichel** [comment]
> @tmichel ezzel tudnál foglakozni?

igen, ezt megírom én. 08.14. után.

**Comment by vbalazs** [comment]
sok sikert a kresz vizsgához!:) :car:

**Comment by tmichel** [comment]
felhasználó státusza is kerüljön át az adatbázisba:
- users táblához új mező: `status`
- címtárból (inetUserStatus) átmásolni minden rekordhoz. fallback `inactive`-ra

jelszóval is valami hasonlót kell:
- kell új mező az users táblába
- át kell másolni a címtárból
- hash-eléssel hogy legyen?
- mi van ha valakinek nincs? lehet ilyen?

**Comment by vbalazs** [comment]
> hash-eléssel hogy legyen?

őőő, ez egy kicsit komplikált, mert a cimtarban ugy van tarolva, hogy base64(append_bytes(jelszohash, salt)). ezt szét kell vágni és két külön oszlopban tárolni. (tehát kell egy usr_password_salt mező is). erre van nekem egy java kódom, ami ezt megcsinálja, kinéztem a címtár forrásából. átírod rubyba java kodot vagy atirjam én?:)

> mi van ha valakinek nincs? lehet ilyen?

elvileg nem lehet. címtárban csak jelszóval lehet benne a tag, viszont ez lehet, hogy egyszer használatos jelszó (ekkor egyébként `inetuserstatus=inactive`, ha jól emlékszem?). viszont a felhasználók, akik csak az adatbázisban vannak, nekik nem lesz jelszavuk, mindenképp `inactive`-ra kell állítani őket. esetleg random jelszót generálni nekik, ezek az emberek valószínűleg nem fognak belépni vagy akkor ticketet adnak fel, hogy miért inaktívak.

**Comment by tmichel** [comment]
Az olyan felhasználóknak, akiknek valamiért nincs hallgatói státusza a címtárban felveszünk egy új értéket: `UNKNOWN`. Ezt tovább kell majd vezetni az enumba is, és a felületre is ki kell tenni egy figyelmeztetést, hogy ha a felhasználó ezt látja, akkor forduljon a supporthoz és megoldjuk.

**Comment by vbalazs** [comment]
#47 -es issue kavarodás miatt, ha benne van már a db-ben a mail címe, neve, stb, akkor azt a címtárban lévő értékkel csapjuk felül. most hirtelen nem emlékszem, hogy így van-e.

**Comment by tmichel** [comment]
> #47 -es issue kavarodás miatt, ha benne van már a db-ben a mail címe, neve, stb, akkor azt a címtárban lévő értékkel csapjuk felül. most hirtelen nem emlékszem, hogy így van-e.

igen ez így van. valójában ez minden esetben így van. ha vir id-val találjuk meg akkor is. mindig a címtárat tekintjük frissnek és mérvadónak.
