### ISSUE TITLE
Migráció JBoss 7.1.3-ra

### ISSUE THREAD

**Issue by vbalazs** [kir-dev/korok#44]
A javaee agent még nem támogatja hivatalosan glassfish4-et ~~Meg kell nézni, hogy a gyakorlatban működik-e, ha nem, akkor nem-e tudunk patchet készíteni az agenthez.~~ és a közeljövőben nem is fogja.

Mivel nem szeretnénk hosszú távon az Oracle-től függni és a jboss most menő, ezért úgy döntöttünk, hogy appcontainert váltunk.

Szükség van a következőkre:
- [x] agent telepítés, tesztelés
- [x] kód módosítás
- [ ] doksi, doksi, doksi

_Ez egy blocker a 2.6-os release stewien való teszteléséhez (tehát az élesbe állításhoz is)._

**Comment by vbalazs** [comment]
Amiket idáig találtam:
- a domain lib/ könyvtárába nem másolódnak be a jarok
- a locale properties fájlok nem másolódnak a lib/classes/ könyvtárba
- egy osztály más csomagba került, így az agent nem találja ([GLASSFISH-17451](https://java.net/jira/browse/GLASSFISH-17451?focusedCommentId=357836&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#action_357836))

~~Mielőtt nagy patchelésbe és fordításba kezdenék teszek egy próbát a [TomEE](http://tomee.apache.org/)-vel.~~
_szerk.: ez a jboss döntés előtt volt, a glassfish agent kompatibilitási vizsgálatát végeztem el_

**Comment by vbalazs** [comment]
Ezt a bug refet lehagytam: _@ Context injection doesn't work in JAX-RS/EJB bean_ ([RESTEASY-532](https://issues.jboss.org/browse/RESTEASY-532))

**Comment by aldaris** [comment]
Csak annyit tennék hozzá, hogy ezeket a mappeléseket az agent szintjén is el lehet végezni, lásd http://docs.forgerock.org/en/openam/10.1.0/admin-guide/index/chap-agents.html Privilege Attributes Processing properties szekció.

**Comment by vbalazs** [comment]
Jól hangzik. Megnézem, köszi!
