### ISSUE TITLE
Elfelejtett jelszó

### ISSUE THREAD

**Issue by vbalazs** [kir-dev/korok#45]
Jelenleg az elfelejtett jelszó szolgáltatást az OpenAM nyújtja, aminek a működését mi patcheltük meg korábban.

Most, hogy dobjuk a címtárat, meg kell vizsgálni, hogy az OpenAM hogy küldte eddig a jelszó emlékeztetőt és hogy ez a működés megvalósítható-e adatbázissal.
Ellenőrizni kell, hogy nem-e küld ki plain text jelszót, nem-e írja a confirmationcode értékét.

Kapcsolódó issue: #19

**Comment by vbalazs** [comment]
Ezt a funkciót PéK-ben valósítjuk meg.
Ki kell találni, hogy mi alapján küldjünk jelszóemlékezetőt. Én a regisztrált e-mail címre szavazok, arra nagyobb eséllyel emlékeznek / tudják az emberek, mint a felhasználónevüket, amit oly' gyakran elfelejtenek.

No meg most a migrálás során lesz egy rakat test([0-9])+ felhasználónevű kliens is, amiket lehet pörgetni, ha valaki elég gonosz akar lenni.

Erről mi a véleményetek?

**Comment by tmichel** [comment]
Szerintem is legyen mail cím alapján. Ha már a user nevet meg lehet kérdezni mail cím alapján akkor értelemszerű lenne, hogy ez is aszerint menjen. 

Bár itt én felvetném, hogy a jelszó emlékeztetőben a felhasználónevét is érdemes lenne elküldeni, és akkor lehetne egységesíteni az elfelejtett felhasználónév és jelszó dolgokat.

**Comment by vbalazs** [comment]
> a jelszó emlékeztetőben a felhasználónevét is érdemes lenne elküldeni

:+1:

**Comment by vbalazs** [comment]
Ez most lehet, hogy nem fér bele péntekig, de néhány napig tudjuk nélkülözni a funkciót. Később kiadunk egy patchet.

**Comment by vbalazs** [comment]
Már csak az időzített task hiányzik a lejárt tokenek időnkénti törlésére és a tesztek
