### ISSUE TITLE
Jelszókezelés LDAP nélkül

### ISSUE THREAD

**Issue by tmichel** [kir-dev/korok#46]
Most, hogy eltávolítjuk az LDAP függőségeket, a jelszót is nekünk kell kezelni. Ez a #43 issue egyik részfeladatából nőtte ki magát.

A következő feladatok vannak:
- Jelszó mentése új felhasználó létrehozásánál. Itt szükséges a jelszót az OpenAM által elvárt formátuma hashelni (SHA1) valamint a saltot adni hozzá. Valamint mindkettőt tárolni.
- A jelszóváltoztatásnál tudni kell ellenőrizni a jelszó helyességét, valamint ahogy az előző pontban is, az új jelszó hash-elni kell.

**Comment by vbalazs** [comment]
> A jelszóváltoztatásnál tudni kell ellenőrizni a jelszó helyességét

itt jelszó policyra gondolsz? azt ki is kellene találnunk :)
kapcsolódó issue #45

**Comment by tmichel** [comment]
egyrészt igen. a kellene egy policy. de konkrétan arra gondoltam, hogy tudjuk ellenőrizni, hogy a jelszava helyes. a jelszóváltoztatásnál elméletileg be kell kérni a régi jelszót is mindig. ha most nem így van, akkor meg kell változtatni a felületet is.

**Comment by tmichel** [comment]
fixed in 6162136480db49624933a56ff771adc8c77348f2
