### ISSUE TITLE
Admin felület - új felhasználó hozzáadása

### ISSUE THREAD

**Issue by vbalazs** [kir-dev/korok#48]
Át kell nézni az admin felületen, hogy csak érvényes felhasználókat lehessen létrehozni.

Bekerült egy felhasználó pl. ékezetes uid-del. Meg kell vizsgálni, hogy még van-e valahol valamilyen rés, amivel érvénytelen felhasználókat lehet létrehozni.

**Comment by tmichel** [comment]
Lehetséges, hogy némi adminisztratív változás is szükséges lenne, hogy csak kijelölt személy férhessen hozzá az éles adatbázishoz, hogy ne történjen kézzel belenyúlás meg random import. Vagy ha ezekre mégis akkora igény van, akkor kell egy lista, amin végig lehet menni és kivel kell egyeztetni stb.

Sőt, ha a "kézzel importra" valós igény van, akkor lehetséges, hogy az admin felületet kellene kiegészíteni, ahol lehet ellenőrizni az adatok helyességét.
