### ISSUE TITLE
Kitöltetlen szobaszám megjelenítése

### ISSUE THREAD

**Issue by vbalazs** [kir-dev/korok#51]
A szobaszám megjelenítése valamiért nem stimmel migrálás után, pl. esetemben ez jelenik meg:
_Szoba  null null_

**Comment by tmichel** [comment]
Azt hiszem ez én voltam. 

``` java
public String getFullRoomNumber() {
    return String.format("%s %s", dormitory, room);
}
```

[forrás](https://github.com/kir-dev/korok/blob/master/sch-pek-domain/src/main/java/hu/sch/domain/user/User.java#L575)

Okosítani kell a függvény kimenetén. Ma este megpróbálok rá időt szakítani.
