### ISSUE TITLE
Kör adatlap - bizonyos esetben a posztok 8x jelennek meg

### ISSUE THREAD

**Issue by vbalazs** [kir-dev/korok#52]
Pl. A kir-dev kör adatlapján bizonyos posztok 8x íródnak ki egymás után.
Jelenleg a jboss provided hibernete modult használjuk, gyanús, hogy hibernate bug. De meg kell vizsgálni pontosan és kitalálni a megoldást.

Ha az újabb hibernate megoldja, akkor több lehetőség van:
- jboss hibernate modul frissítés (annyira nem szép)
- kockáztatni és a jboss modul ellenére az alkalmazásba csomagolni
- az alkalmazásba csomagolni és létrehozni egy deployment xml-t, amiben kizárjuk a jboss hibernate modult (azt hiszem lehet ilyet)

**Comment by tmichel** [comment]
development környezetben glassfishen a ddfb5d2702c774f7b65e755a0e89cae114d6feb7 commitnál még jó.
