### ISSUE TITLE
Képek elérési útjában nagybetűk

### ISSUE THREAD

**Issue by vbalazs** [kir-dev/korok#53]
Meg kell vizsgálni, hogy ez problémát okoz-e, illetve jó lenne, ha nem lennének :) a user neveket is lehet, hogy kisbetűsíteni kellene.

migrálást elvileg már nem tudunk csinálni, mert visszaengedjük a felhasználókat szombatra. erre lehet, hogy kell egy szkript, ami javítja vagy nem tudom.

`$ ls applications/korok/photos/`
`0  1  9  a  b  c  d  e  E  f  g  h  i  j  J  k  K  l  m  n  o  p  q  r  s  t  u  v  w  x  y  z`

**Comment by tmichel** [comment]
041987263f6006be57d634950dac3b3642a6a555 megoldja ezt a problémát
