### ISSUE TITLE
Közösségi pontok nem látszanak

### ISSUE THREAD

**Issue by hgabor** [kir-dev/korok#6]
Ha az aktuális félévben nem kapott KP-ot, csak az előzőben, a felvételihez használt pontoknál nem jelenik meg az aktuális félév.
Pl.: https://profile.sch.bme.hu/korok/userhistory/id/26726?17 hiányzik a 2012/2013 ősz sor.

A KFB exportnál minden okés.

**Comment by Ksisu** [comment]
Na a megjelenésbe itt kerülnek bele a szemeszterek:

sch-pek-web/src/main/java/hu/sch/web/kp/user/UserHistory.java 129-132 sor

``` Java
        List<SemesterPoint> semesterPoints = new ArrayList<SemesterPoint>();
        for (Semester s : userManager.getAllValuatedSemesterForUser(user)) {
            semesterPoints.add(new SemesterPoint(s, userManager.getSemesterPointForUser(user, s)));
        }
```

És mivelhogy így van specifikálva a használt függvény:

``` Java
    /**
     * Visszaadja az összes olyan szemesztert csökkenő sorrendben, ahol az adott
     * felhasználónak van elfogadott pontkérelme.
     *
     * @param user - A felhasználó, akit vizsgálunk
     * @return A szemeszterek, amikor van elfogadott pontkérelme
     */
    public List<Semester> getAllValuatedSemesterForUser(User user);
```

Ezért szerintem simán csak a webes rétegben kéne belevarázsolni a plusz sorokat.

**Comment by vbalazs** [comment]
https://github.com/kir-dev/korok/commit/7ee8cab0a9851de3692ab2c880e272dc95b51808#commitcomment-4462497

**Comment by Ksisu** [comment]
Na lett neki egy új branch és ment egy commit is, ami lényegében javítja. Kicsit át lett írva a dolog.
- UserManagerBean.getSemesterPointForUser-nek ha az aktuális vagy jövőbeni szemesztert adunk meg akkor nullát ad vissza(aktuális szemeszternél eddig rosszat adott)
- SemesterPoint eddig a webes rétegben volt(UserHistoryban :package: láthatósággal) ezt átvittem a domainbe
- UserManagerLocal.getAllValuatedSemesterForUser-t csak egy helyen volt használva és ott is igazából még pontok is érdekelték ezért ezt átalakítottam getAllValuatedSemesterWithPointForUser-re és egy SemesterPoint listával tér vissza
- UserHistory-ban kivettem az egész szemeszter- utána pontlekérdezős részt és az előbbi függvényt használja

Még teszteket kéne írni, meg átgondolni ezt:

A UserManagerBean.getSemesterPointForUser-t igazából csak a UserManagerBean.getAllValuatedSemesterWithPointForUser használja, ráadásul egy user lekérdezésnél minden szemeszternél, így lehet érdemesebb volna összevonni a kettőt. @tmichel @vbalazs vélemény?

**Comment by vbalazs** [comment]
> A UserManagerBean.getSemesterPointForUser-t igazából csak a UserManagerBean.getAllValuatedSemesterWithPointForUser használja, ráadásul egy user lekérdezésnél minden szemeszternél, így lehet érdemesebb volna összevonni a kettőt.

szerintem ne vondd össze. jó, ha nincsenek nagy metódusok és ahogy látom a `getSemesterPointForUser` implementációja nem triviális. viszont mivel már csak ejb-ből van használva priváttá lehet tenni...

_szerk: a queryk viszont tenyleg eleg szerencsetlenul vannak megoldva. azok valoban osszevonhatok es kodbol kezelhetok._

**Comment by Ksisu** [comment]
Na a UserHistoryFixing branch-ben javítva lett, lett hozzá teszt írva, viszont a teszt összetettsége miatt, csak "részlegesen" tud lefutni (nem tudja ellenőrizni az aktuális szemeszert, aminek ugye 0 pontosnak kéne lennie), amint a tesztkörnyezet is megépül köré mehet is a masterbe. Pluszba teszteltem "kézzel", ott is jónak tűnt.
