### ISSUE TITLE
Profilképek megjelenítése

### ISSUE THREAD

**Issue by vbalazs** [kir-dev/korok#60]
Kinyomoztam mi a para.
Szóval az újra feltöltött képekkel tényleg működik, a hiba a migráló scriptben volt :(
a script így mentette:

```
(t,tmichel,6de8fe7a549dda2a234b6a5c1d510dab04b94801.png)
```

pékből feltöltés után már jó a mező tartalma:

```
b/balo/634c4bb4a6601da7813a3ef3c789c48b8b107097.jpg
```

Ki kell javítani a meglévőket vagy újramigrálni a képeket, de az időközben feltöltötteket (amik nem `(` karakterrel kezdődnek) nem szabad bántani.

Újramigrálás esetén related #53 (migrálás óta feltöltött képekre szintén ügyelve)

**Comment by tmichel** [comment]
ez nagyon érdekes. pedig én teszteltem a migrálást és akkor ment. valahogy a `File.join` nem akarta összefűzni rendesen. ennek utána kellene még járni.

a migráló scriptre már nincs szükség. lehet hogy felesleges lenne vele még időt tölteni. egy sql megoldja ezt a problémát. reményeim szerint.

**Comment by vbalazs** [comment]
> egy sql megoldja ezt a problémát. reményeim szerint.

Ok, de az #53 -hoz akkor is kell valami okosság és itt is kisbetűsíteni kell. Végülis lehet két lépésben.

**Comment by tmichel** [comment]
ez igaz. akkor szerintem írok egy scriptet, ami kijavítja mindkettőt. nem kell két lépésben.

**Comment by tmichel** [comment]
az új képek feltöltésénél is figyelni kell majd az elérési utak generálására. [vonatkozó kód](https://github.com/kir-dev/korok/blob/master/sch-pek-ejb-impl/src/main/java/hu/sch/ejb/image/ImageSaver.java#L84)

**Comment by vbalazs** [comment]
ezzel van még teendő?

**Comment by tmichel** [comment]
nincs. lezárom. :)
