### ISSUE TITLE
Kézi reg után a megerősítés nem megy

### ISSUE THREAD

**Issue by hgabor** [kir-dev/korok#64]
<pre>
Ha problémája akadt a Körök, vagy a Profil oldalakon, akkor írja ide:
-------------------------------
Felhasználói azonosító:
-----------------------
gyadam90

Meglátogatott oldal:
---------------------
https://profile.sch.bme.hu/profile

Hibajelenség:
--------------
Külsősként elvileg kaptam SSO-account-ot, de jelszót nem kaptam, a megerősítő link pedig nem csinál
semmit, úgyhogy nem tudok belépni. 
</pre>

**Comment by hgabor** [comment]
Újabb ticket, ugyanezzel :)

<pre>
https://"profile.sch.bme.hu"/profile/confirm/code/fTEZVL8WNVT8JeLZavhD_sUOo3luI7L9vTugXZrlfz15kmnPClo4T-VvNC2u5nNv
[...] kiszedve az idézőjeleket, csak a VIR Login oldal fogad, kér felhasználónevet, jelszót. [...]
</pre>

**Comment by vbalazs** [comment]
Egyrészt frissítettem a policyt, de egyelőre nem úgy tűnik, hogy átengedi az url-t.

ConfirmPage-t biztos, hogy át kell alakítani:
- homepage-re való redirecteket kiszedni, mert azok csak bejelentkezéssel érhetők el
- kell egy státusz oldal, amin megjelenítjük, hogy sikerült / nem sikerült
- ejb-ben jó lenne logolni, hogy user aktiválás történt (confirm metódus)
