### ISSUE TITLE
Dátum formázási hiba

### ISSUE THREAD

**Issue by vbalazs** [kir-dev/korok#65]
https://profile.sch.bme.hu/korok/showuser/id/15148

meg kell nézni pontosan mikor - de tippre, ha nincs meg a tagság kezdeti dátuma ez jelenik meg:  
`2085.09.01. - 1990.07.01.`

Ez elég bután néz ki. vagy wicket migrálással romlott el vagy eddig is ilyen volt :D

**Comment by Ksisu** [comment]
Ilyen sort találtam a backup sqlben:

```
1216    196 15148   2085-09-01  1990-07-01
```

tippre ez az a sor ami a csoporttagságát rögzíti :)

**Comment by vbalazs** [comment]
jó meglátás, ha már ott voltam megnéztem, hogy van-e még hasonló:

```
 select * from grp_membership where membership_start > NOW() or membership_end > NOW();
  id  | grp_id | usr_id | membership_start | membership_end 
------+--------+--------+------------------+----------------
 1216 |    196 |  15148 | 2085-09-01       | 1990-07-01
 3699 |     63 |  13778 | 1987-09-01       | 2020-05-03
(2 rows)
```

ezeket kézzel kell sajnos javítani az éles db-ben is.
