### ISSUE TITLE
Gólyák hozzáférés szabályozása

### ISSUE THREAD

**Issue by vbalazs** [kir-dev/korok#66]
Ez ldap filter policyvel volt megoldva, hogy a gólyák ne tudjanak hozzáférni a PéK belső oldalaihoz.

Mivel már nincs ldap, ezért ezt a PéK kódjából kell kezelni.

Ha a User `StudentStatus` értéke `NEWBIE`, akkor gólya, nekik csak a regisztrációs / elfelejtett azonosítók varázslókat szabad engedélyezni az alkalmazásból, minden más hozzáférési kísérlet esetén a 403-as oldalt kell mutatni.

Ezt a gólyaidőszak kezdetéig javítani kell.

**Comment by tmichel** [comment]
Már nincsenek megkülönböztetve a gólyák. Az auth.sch-tól nem kapunk ilyen információt.
