### ISSUE TITLE
Profil webszolgáltatás az auth.sch projekt számára

### ISSUE THREAD

**Issue by vbalazs** [kir-dev/korok#71]
Szükséges egy webszolgáltatás, amin keresztül az auth.sch különböző azonosítók alapján elkérheti a felhasználói profilt.

https://trello.com/c/gL3v9JUw
https://redmine.kirdev.sch.bme.hu/projects/vip/wiki/WS_Profile

**Comment by zolij** [comment]
ezeket kéne még implementálni
- givenName
- sn
- cn

további hiány:
- eduPersonEntitlement, de ez a a #72 kijavításával egy ideig húzható

Emellett pedig jó lenne elgondolkodni az egységesítésen (a loginkor átkerülő és a webservice-n átjövő adat formátuma bizonyos esetekben más, lásd: schacPersonalUniqueId).
