### ISSUE TITLE
Közösségi pontszámítás központosítása

### ISSUE THREAD

**Issue by tmichel** [kir-dev/korok#75]
Jelenleg két helyen kétféleképpen számoljuk ki a közösségi pontokat:
- A felületen megjelenő pontok. [`UserManagerBean#getAllValuatedSemesterWithPointForUser`](https://github.com/kir-dev/korok/blob/master/sch-pek-ejb-impl/src/main/java/hu/sch/ejb/UserManagerBean.java#L209)
- A KFB exportnál generált CSV, ami minden bizonnyal jó eredményeket ad. [`getpointsforsemester`](https://github.com/kir-dev/korok/blob/master/resources/sql/vir-schema-current.sql#L69)
- át kell nézni a `ValuationManagerBean` osztályt, főleg a KBME-s részt, mert @zolij [kommentje](https://github.com/kir-dev/korok/issues/75#issuecomment-31324130) alapján még ez is idetartozhat.

Ezt a két számítást kéne egységesíteni. Ehhez még hozzájön a #67 issue is.

A pontos képlet megtalálható a HK által kiadott [kollégiumi felvételit szabályozó dokumentum](http://vik.hk/files/kfk_2013_2014_tavasz.pdf) 2.1.1-es pontjában

Az egységesítésre két lehetséges irány:
- származtatott érték lévén minden alkalommal a kezdetektől számoljuk.
- a másik út, hogy a kiszámolt értékeket eltároljuk egy külön táblában (`id, user id, group id, semester, point`), így egy félévre kiszámolni a közösségi pontokat triviálissá válik, ahogy listázni és exportot készíteni is.

Én a második módszert támogatom, mert a hosszútávú célunk a karbantarthatóság, és ez ugyan több adatot, de egyszerűbb kódot eredményezne.

Annyiban kiegészül még a dolog, hogy jelenleg a felületen az összesített pontok megjelenítése néha érdekes számolja az eredményt. Ez megoldódik, ha a pontokat előre kiszámítjuk és a felületen már csak ezeket jelenítjük meg. Annyival egészül még ki a dolog, hogy a még nem értékelt aktuális félévet is érdemes megjeleníteni az értékelési időszak alatt, de mutatni kell, hogy még nem került lezárásra az értékelés, így nincs "nincs pontja" a usernek az adott félévre.

_szerkesztve: 2013.12.30., 2014.01.01._

**Comment by hgabor** [comment]
Mi a hiba a felületen lévő pontoknál? A Java kód kicsit nyakatekert, de helyesnek tűnik.
BTW, a képlet **nem** rekurzív, összesen két félév pontozásából jön ki a felvételi pontozás.

**Comment by zolij** [comment]
ha már tárolt eljárások és közösségi pontok, akkor a KBME számára [közösségi pontokat számoló funkciót](https://github.com/kir-dev/korok/blob/master/sch-pek-ejb-impl/src/main/java/hu/sch/ejb/ValuationManagerBean.java#L800) is ide lehetne venni. Kérdés persze hogy szükség van-e rá, mert a KBME specifikációban nem látom nyomát (mondjuk a #71 -ben szívesen venném a közösségi pontokat:)).

**Comment by tmichel** [comment]
@hgabor és tényleg. csak azért keveredtem meg, mert a kör vs összesített összecsúszott a fejemben. ha az előző féléves összesítettet kellene, akkor már tényleg rekurzívvá válhatnak, de így nem. módosítom is a szövegezést.

valamint a java kód azért rossz, mert nem veszi figyelembe az előző féléves pontot.

**Comment by hgabor** [comment]
Akkor ideírom az algó magyarázatát, röviden:

Végigmegy minden elfogadott, érvényes pontigényen, és hozzáadja a pontot a megfelelő bejegyzéshez:

``` java
if (!allPoints.containsKey(s)) {
    allPoints.put(s, new HashMap<Group, Integer>());
}
HashMap<Group, Integer> semesterGroupPoints = (HashMap<Group, Integer>) allPoints.get(s);

int point = p;
if (semesterGroupPoints.containsKey(g)) {
    point += (int) semesterGroupPoints.get(g);
}
semesterGroupPoints.put(g, point);
```

Viszont ezután megnézi, hogy van-e rákövetkező félév:

``` java
//Group point add to after point request semester
Semester ns = s.getNext();
//Not added if the next semester is current or future
if (systemManager.getSzemeszter().compareTo(ns) <= 0) {
    continue;
}
```

És ha igen, ahhoz is hozzáadja (ugyanúgy, mint fent).

Szóval mint mondtam, nyakatekert :)
Nem az összesítéskor veszi figyelembe az előző pontozást, hanem az összegzéskor a következő félévhez is hozzáadja - de a végeredményben ugyanaz.

Amúgy is, ha hibás lenne, akkor a supporton keresztül már tudnánk róla :)

**Comment by tmichel** [comment]
Éreztem, hogy valamikor már megértettem ezt és akkor jónak tűnt. Sebaj. Ettől függetlenül ki lesz dobva és központosításra kerül.

**Comment by tmichel** [comment]
Ez lényegében megoldódott a https://github.com/kir-dev/korok/pull/92 pull requesttel.

A KBME-s integráció még egy tisztázatlan kérdés. @Ksisu tud talán felvilágosítást adni. Erről majd nyitunk új issue-t, ha előjön.
