### ISSUE TITLE
Configuration osztály singletonná alakítása

### ISSUE THREAD

**Issue by tmichel** [kir-dev/korok#76]
Jelenleg a [`Configuration`](https://github.com/kir-dev/korok/blob/master/sch-pek-domain/src/main/java/hu/sch/domain/config/Configuration.java) osztály egy statikus osztály. Ez a tesztelhetőséget nagyban nehezíti. 

A `Configuration`-t át kellene alakítani, hogy singleton legyen, így lecserélhető lenne az implementáció a teszteknél. Ezen kívül az alkalmazásban is refaktorálni kell azokat az  osztályokat, amik használják a `Configuration`-t

**Comment by tmichel** [comment]
A tesztelés miatt a singletont, még lehet, hogy felül kell vizsgálni.

**Comment by tmichel** [comment]
Most kezdem volna használni az új refaktorált `Configuration` osztályt és rögtön kibukott, hogy nem teljesen a jó irányba mentünk el. Az egész célja a tesztelhetőség javítása lett volna, de közben sikerült belefutni abba, hogy a közvetlenül tesztelt osztályban ki tudom cserélni a `Configuration` példányt, de a járulékos osztályokban már nem.

Lehet, hogy meg kellene szüntetni a `Configuration` singleton mivoltát, és inkább egy factory mintát bedobni helyette.

**Comment by messo** [comment]
A megoldas: DI. A Condfigurationt fuggosegkent kell definialni minden osztalynal. Az hogy milyen scope reszletkerdes (de nyilvan Singleton). A tesztelhetoseghez az kell hogy minden mockolando peldanyt fuggosegkent kezeljetek. Az hogy ha ehhez egy factoryt csinaltok es azt mockoljatok csak egy folosleges lepes, es nem logikus.

**Comment by tmichel** [comment]
A DI azért para, mert van olyan eset, amikor a konfigra olyan osztályban van szükség, ami nem menedzselt. Persze mindenhol megoldható, hogy pl paraméterként kapja meg a metódus, te nem túl szép. Átgondolom.

**Comment by messo** [comment]
Guice ;)

**Comment by tmichel** [comment]
Biztosan nem fogok egy felesleges technológiát behozni, amikor a sima CDI is megfelel jelenleg.

**Comment by messo** [comment]
Amúgy meg wicket-cdi, megy mint az álom, ha nem konténer adja a példányt akkor is. Csak azért szóltam közbe, hogy nehogy a nyúl vigye a puskát, ne a jó logikát csorbítsátok el.

**Comment by tmichel** [comment]
Az sch-pek-2.7.0-as kiadással ez lezárult. CDI `ApplicaitonScoped` bean lett.
