### ISSUE TITLE
OpenDj SDK bevezetése springldap helyett

### ISSUE THREAD

**Issue by vbalazs** [kir-dev/korok#8]
Jelenleg springes ldap könyvtárral kezeljük a címtárunkat, ezen szeretnénk változtatni és OpenDJ sdk-t használni, amelyet a ForegeRock fejleszt.

A kód egy részét már migrálta @messo , amely most a 3.0-s branchben van, nem kell nulláról kezdeni a munkát.

Jó lenne egy **performanciateszt** előtte / utána csak, hogy lássuk, hogy ezen a téren nyertünk-e a használatával. (kód olvashatóság / karbantarthatóság tekintetében mindenképp nyerünk)

Meg kell vizsgálni, hogy a migrálást lehetne-e **tesztekkel kísérni**, hogy a refaktorálással biztos ne rontsuk el a működő funkciókat.

**Comment by aldaris** [comment]
Like. Az API még nem teljesen stabil mondjuk, az OpenAM által használt p3-as verzió kapcsolatkezelés-ügyileg elég stabilnak tűnik, a nightly viszont még azt hiszem küszködik néhány grizzly problémával.

**Comment by vbalazs** [comment]
észleltem, mert ha jól láttam csak SNAPSHOT van a maven repokban és el is breakelt, amikor próbáltuk lefordítani a 3.0-ás branchet :) kicsit kalapáltunk rajta és jó lett. De hosszabb távon remélhetőleg megtérül.

**Comment by vbalazs** [comment]
@NPeete

**Comment by vbalazs** [comment]
> néztem teljesítménytesztet:
> http://www.dirmgr.com/blog/2011/5/31/comparing-java-ldap-sdk-performance.html
> igaz ez 2011-es de sebaj
> egész jól néz ki ez az unboundID, utánanézek
> https://www.unboundid.com/products/ldapsdk/

(by @NPeete )

**Comment by tmichel** [comment]
az unboundid ldap sdk-ra esett a választás végül.

**Comment by aldaris** [comment]
Szomorú, a 2.6-os DJ SDK nemsokára ki lesz adva pedig :(

**Comment by vbalazs** [comment]
:broken_heart:

**Comment by tmichel** [comment]
fixed 73cce09deba4fc2cacedbb3d00374be20917a66e >> ab28c7145c720b5a2c421ee2c157e1c95f8bd278
