### ISSUE TITLE
LostPasswordToken equals és hashCode

### ISSUE THREAD

**Issue by tmichel** [kir-dev/korok#80]
A `LostPasswordToken` entitásról lemaradt az `equals` és `hashCode` metódusok implementálása.

```
00:15:56,935 WARN  [org.hibernate.mapping.RootClass] (ServerService Thread Pool -- 52) HHH000038: Composite-id class does not override equals(): hu.sch.domain.user.LostPasswordToken
00:15:56,936 WARN  [org.hibernate.mapping.RootClass] (ServerService Thread Pool -- 52) HHH000039: Composite-id class does not override hashCode(): hu.sch.domain.user.LostPasswordToken
```

Ehhez kapcsolódik, hogy egy "ős" entitást létre kéne hozni, amiben ezeket központosítani lehetne és minden entitás ebből származna.

**Comment by vbalazs** [comment]
biztos, hogy szükség van ős entitásra? milyen mezőket tartalmazna? mi lenne a szerepe?

**Comment by messo** [comment]
Ez esetleg? http://docs.oracle.com/javase/7/docs/api/java/util/Objects.html#hash(java.lang.Object...)

**Comment by vbalazs** [comment]
nem rossz, igazabol netbeans generalta, nem neztem meg, hogy hogyan lehetne maskepp

**Comment by tmichel** [comment]
@vbalazs az ős entitásba én id-t tennék, hashcode-t és equalst. úgy is mindig az id alapján megy az equals. a hashcodenak ez is elég sokszor.

**Comment by vbalazs** [comment]
> az ős entitásba én id-t tennék, hashcode-t és equalst. úgy is mindig az id alapján megy az equals. a hashcodenak ez is elég sokszor.

rossz. és ha mentés előtt Set-ben tárolnál több új elemet?:) azoknak mind null az id-ja, a másodikat már nem tenné bele... aztán fél napig debugolhatnád, hogy WTF (been there, done that)

**Comment by tmichel** [comment]
nem mondom, hogy nincsenek hátulütői, de viszont így meg minden entitáshoz meg kell írni az `equals`-t, ami majdnem hogy sorról sorra megegyezik mindenhol.

**Comment by vbalazs** [comment]
épp ez a lényege szerintem az equals meg hashcode metodusoknak, hogy minden osztálynál mást jelent az, hogy két példány egyenlő... Adott esetben lehet, hogy néhány dolog nem számít (pl. last modified), de ugyanez a mező meg egy másik osztálynál pont megkülönböztető mező.

**Comment by tmichel** [comment]
ez logikus, csak az entitásoknál általában az id egyedi, így ez alapján
nézzük az egyenlőséget. persze ez nem oldja meg a `null` id problémát.
lehet, hogy majd egy külön util osztályba kellene kiemelni. lehet, hogy
elég lenne egy interfész amiben a `getId()` van. sőt. talán ez a legjobb,
mert akkor központosíthatjuk a kódot, de közben megmarad az, hogy mindenhol
külön kell implementálni.

2014/1/12 Balazs Varga notifications@github.com

**Comment by vbalazs** [comment]
Továbbra sem látom, hogy ennek mi haszna lenne. Egy struktúrában akarsz tárolni usert meg valuationt pl?

**Comment by tmichel** [comment]
Ennek én egyetlen hasznát látom: kód újrahasznosítás. az esetek nagy részében az `equals` ugyanaz. id-t hasonlít össze, meg típust.

**Comment by tmichel** [comment]
ezt lezárom, maradunk a jelenlegi felállásnál: minden entitáshoz saját equals és hashCode ha szükség van rá.
