### ISSUE TITLE
Öregtag - tag inkonzisztencia kivizsgálása

### ISSUE THREAD

**Issue by vbalazs** [kir-dev/korok#81]
Úgy tűnik valakiknek valahogyan sikerült több olyan esetet generálniuk, amikor egy ember egyszerre tag és öregtag egy körben:

Lásd a Felező körtagságát itt:
https://profile.sch.bme.hu/korok/showuser/id/23607

De a Felező kör öregtagjai között lapozgatva is találni ilyet.

Ki kell vizsgálni, hogy ez hogyan lehetséges, normális-e és hogy kijavítsuk-e.

**Comment by Ksisu** [comment]
Annyi történt, hogy valamikor az egyik felező "körvezető" létrehozott egy egyedi poszttípust aminek a "tag" nevet adta. Így ha valaki megkapja ezt a posztot és utána öregtaggá válik, akkor a neve mellett szerepelhet egyszerre, a tag és az öregtag is. Ez történt a fenti esetben is.

**Comment by Ksisu** [comment]
Az a döntés született, hogy törölhetjük ezt az izgalmas posztot.

**Comment by Ksisu** [comment]
Localba teszteltem az egyszerű kitörléses dolgot. Úgy néz ki működik.

``` sql
DELETE FROM poszt WHERE pttip_id = 291;
DELETE FROM poszttipus WHERE pttip_id = 291;
```

**Comment by vbalazs** [comment]
Szerintem ok.

**Comment by tmichel** [comment]
Szerintem is. Este kitoljuk élesre, aztán le lehet majd zárni ezt az issue-t.

**Comment by tmichel** [comment]
a változtatásokat az éles adatbázisba is átvezettem.
