### ISSUE TITLE
email újraküldése regisztrációról

### ISSUE THREAD

**Issue by salierri** [kir-dev/korok#91]
Lehetséges legyen hibás email-küldésnél újraküldeni a regisztrációs emailt az új felhasználóknak.

**Comment by vbalazs** [comment]
szerintem felesleges ez a ficsor:
- ennek nem szabadna elofordulnia, ez egy kiveteles eset -> rendszermonitorozassal orvosolhato
- ha valahogy megis elofordul kerjen jelszoemlekeztetot. nem tudom, hogy ilyenkor van-e valami egyeb aktivalas es ennel elfelejtett jelszonal csinalunk-e valamit, ezt kene inkabb megnezni.

**Comment by tmichel** [comment]
Szerintem a jelszó emlékeztető nem jó, mert a regisztrációját meg kell erősíteni. Viszont lehet, hogy felül kéne vizsgálni a regisztrációs folyamatot - ez úgyis változni fog az auth.sch bevezetésével. Sőt kifejezetten át kell gondolni, mert a régi felhasználókezelés eltűnik. Az új felületen elvileg nem is kéne lennie jelszó emlékeztetőnek.

**Comment by tmichel** [comment]
Ez már biztosan nem kerül megvalósításra. A 3.0-ás verzióban már nem is lehet közvetlenül regisztrálni a rendszerbe. Erre csak auth.sch-n keresztül lesz lehetőség.
