### ISSUE TITLE
Legördülő menü hiba iOS-en

### ISSUE THREAD

**Issue by abelorosz** [kir-dev/korok#93]
iOS eszközön nem működik a legördülő menü.

![image](https://cloud.githubusercontent.com/assets/620148/2915790/57d32d0c-d6b2-11e3-9fda-a107211ce22a.jpg)

**Comment by tmichel** [comment]
Ez minden mobil böngészőben probléma. Az új felület tervezésénél fogunk erre figyelni, de a jelenlegi felületet már nem valószínű, hogy kijavítjuk.
